name: My First WorkFlow
on:
    repository_dispatch:
        types: ["coffee","tea"]
jobs:
    MySimpleJob:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World Action
              run: |
                echo "Hello World"
                echo "### Hello World from MySimpleJob ### ::rocket::" >> $GITHUB_STEP_SUMMARY
                echo "<h1>Test Heading</h1>" >> $GITHUB_STEP_SUMMARY
           